export const ServiceNav = [
  {
    title: "Cross Border Transactions",
    subTitle: "Angel Investment",
    subTitle0: "Foreign Direct Investment",
    subTitle1: "Foreign Entity & Repatriation",
    subTitle2: "International Business Transactions",
    subTitle3: "Joint Ventures",
    subTitle4: "Mergers & Acquisitions",
    subTitle5: "Project Finance",
    subTitle6: "Public Procurement",
  },
  {
    title: "Corporate & Compliance",
    subTitle: "Banking",
    subTitle0: "Business Incorporation",
    subTitle1: "Corporate Counsel",
    subTitle2: "Corporate Due Diligence",
    subTitle3: "Tax",
    subTitle4: "",
    subTitle5: "",
    subTitle6: "",
  },
  {
    title: "Construction & Real Estate",
    subTitle: "Construction",
    subTitle0: "Conveyance",
    subTitle1: "Due Diligence",
    subTitle2: "Factory & Environmental",
    subTitle3: "Mortgage & Hypothecation",
    subTitle4: "Turnkey",
    subTitle5: "",
    subTitle6: "",
  },
  {
    title: "Commercial Transactions",
    subTitle: "Capital Restructuring and Finance",
    subTitle0: "Insurance",
    subTitle1: "Intellectual Property",
    subTitle2: "Maritime & Inland Shipping",
    subTitle3: "Media & Entertainment",
    subTitle4: "Startups",
    subTitle5: "",
    subTitle6: "",
  },
  {
    title: "Dispute Resolution",
    subTitle: "Arbitration",
    subTitle0: "Litigation",
    subTitle1: "Mediation",
    subTitle2: "Negotiation",
    subTitle3: "",
    subTitle4: "",
    subTitle5: "",
    subTitle6: "",
  },
  {
    title: "Employment & Labor",
    subTitle: "Compliance",
    subTitle0: "Labor Code",
    subTitle1: "Service Rules",
    subTitle2: "Termination & Unlawful Dismissal",
    subTitle3: "",
    subTitle4: "",
    subTitle5: "",
    subTitle6: "",
  },
];
